#!/bin/sh

# Copy devices from /lib/udev/devices.
/bin/cp -ar /lib/udev/devices/* /dev

# Launch udev daemon, make sure it's not running first.
if ! /bin/pidof -q -s udevd; then
	/sbin/udevd --daemon
fi

# Coldplug devices and wait for the queue to be processed.
/sbin/udevadm trigger --type=subsystems --action=add
/sbin/udevadm trigger --type=devices    --action=add
/sbin/udevadm settle

# End of file.
