#!/bin/sh
#
# /usr/bin/runjobs: run all executables in specified directory
#

if [ "$1" = "" ]; then
	cat >&2 <<EOF
Usage: ${0##*/} DIR
Run all executables in specified directory.
EOF
	exit 1
fi

cd "$1" || exit 2

for file in ./*; do
	if [ -f "$file" ] && [ -x "$file" ]; then
		nice -n 19 "$file"
	fi
done

# End of file.
