.\" rotatelog(8) manual page
.Dd October 28, 2023
.Dt ROTATELOG 8
.Os
.Sh NAME
.Nm rotatelog
.Nd rotate system log file
.Sh SYNOPSIS
.Nm rotatelog
.Em logfile
.Sh DESCRIPTION
.Sy rotatelog
is a very simple
.Xr sh 1p
script to rotate the system log file in
.Pa /var/log
directory.
If
.Pa /var/log/ Ns Em logfile
exists, it will be copied to
.Pa /var/log/old/ Ns Em logfile Ns .1
and nulled afterwards.
Meanwhile, if
.Pa /var/log/old/ Ns Em logfile Ns .1
already exists, it will be copied to
.Pa /var/log/old/ Ns Em logfile Ns .2
first.
If second logfile exists, it will be copied to the third and so on, up
to 9. If
.Pa /var/log/old/ Ns Em logfile Ns .9
exists, it will be nulled, and overwritten by eight copy.
This is a pretty simple scheme used by default in Zeppe-Lin system: just
call this script as weekly
.Xr crond 8
task on every file in
.Pa /var/log
directory.
.Pp
If you need something else, see
.Xr syslog.conf 5
for log rotation, or
.Xr logrotate 8
for something more sophisticated.
.Sh SEE ALSO
.Xr syslog.conf 5 ,
.Xr logrotate 8
.\" vim: cc=72 tw=70
.\" End of file.
